meta_product_name: "Chez Valou Pâtisserie"
meta_title: "Chez Valou Pâtisserie"
meta_description: "Chez Valou Pâtisserie - Création de pâtisseries sur-mesure, à votre goût - Livraison à domicile dans la région de Bordeaux"
meta_keywords: "Chez Valou"
meta_image: "logo.png"                       # should exist in `app/assets/images/`
